export const TRIGGER_LOGIN = "TRIGGER_LOGIN";
export const TRIGGER_LOGIN_SUCCESS = "TRIGGER_LOGIN_SUCCESS";
export const TRIGGER_LOGIN_FAILED = "TRIGGER_LOGIN_FAILED";

export const TRIGGER_SIGN_UP = "TRIGGER_SIGN_UP";
export const TRIGGER_SIGN_UP_SUCCESS = "TRIGGER_SIGN_UP_SUCCESS";
export const TRIGGER_SIGN_UP_FAILED = "TRIGGER_SIGN_UP_FAILED";

export const TRIGGER_LOGOUT = "TRIGGER_LOGOUT";

export const TRIGGER_CREATE_TASK = "TRIGGER_CREATE_TASK";
export const TRIGGER_CREATE_TASK_SUCCESS = "TRIGGER_CREATE_TASK_SUCCESS";
export const TRIGGER_CREATE_TASK_FAILED = "TRIGGER_CREATE_TASK_FAILED";

export const GET_ALL_TASK = "GET_ALL_TASK";
export const GET_ALL_TASK_SUCCESS = "GET_ALL_TASK_SUCCESS";
export const GET_ALL_TASK_FAILED = "GET_ALL_TASK_FAILED";

export const TRIGGER_CREATE_TYPE_BUTTON = "TRIGGER_CREATE_TYPE_BUTTON";
